### ISSUE TITLE
release 0.0.0-RC1

### ISSUE THREAD

**Issue by stbischof** [congo-cc/ccc-mvn#3]
Staging-Repo: https://s01.oss.sonatype.org/content/repositories/orgcongocc-1006/

@revusky would you be okay with a release `0.0.0-RC1` ?

**Comment by revusky** [comment]
Well, I would prefer to start numbering at a higher number. I don't know if you know the whole history of this. My original JavaCC "fork" was called FreeCC and I believe I put out 4 releases between mid-2008 and the beginning of 2009. I started the numbering at 0.9 so there was a 0.9.0, a 0.9.1, a 0.9.2, and a 0.9.3. You can see an announcement for the last one [here](https://groups.google.com/g/freecc-devel/c/1bK3HVyq_Qk). I picked up the code at the very end of 2019 and made enough improvements that I then put out a 0.9.4, which was just about 11 years after the prevous one. https://freshfoss.com/projects/freecc

And then after that, I decided to call the project "JavaCC 21". A grand experiment that is now coming to an end, I guess. Part of the experiment was just to see whether I could get away with eschewing all this release/versioning stuff and just tell people to download the thing and use it. But, apparently, one cannot get away with that. That would be too easy and thus, is somehow not allowed.

But anyway, the current CongoCC is actually *vastly* more advanced than those previous FreeCC releases were. And those versions of FreeCC were in turn *vastly* more advanced than *any* version of legacy JavaCC that has ever existed! They already had the `INJECT` directive, for example -- which I consider a very key feature since it actually makes JJTree usable!

Well, truth told, I don't have any particular ideas about version numbering, since, as you doubtless have inferred, I tend to think the whole thing is basically BS. (Certainly when the legacy POC implementation that is hosted on javacc.org is version 7.0.x and nobody seems to object to that!) We could resume the old numbering, going to 0.9.5. Another few releases and then we put out a 1.0RC and a 1.0final. Something like that...

Actually, now that I think about it, maybe we could just start at 2.x, the theory being that JavaCC21 was really CongoCC 1.x....

Anyway, what do you think? I might want to think about this a bit more, but to answer your question, I think we should start with a much higher number.

**Comment by stbischof** [comment]
I think.
JavaCC21 -> 0.x
CongoCC -> 1.x

i also would ognore all 7.X and 0.95 ( others will not understand..)

The question is also, whether current CongoCC I just include is ready to release.

**Comment by revusky** [comment]
> I think. JavaCC21 -> 0.x CongoCC -> 1.x

Well,... if the old FreeCC was at 0.9.4 three years ago, and JavaCC21 is just a renamed FreeCC, then in the last three years, we should have passed 1.0. I say that somewhat tongue-in-cheek because I don't actually think these numbers mean anything, but... Still, honestly, it seems reasonable to me that Congo should start at 2.x. 

Not that I really care about this that much. Mostly I just don't want to start at 0.0 because it implies that the thing was just written yesterday, which is really very far from being the case!

But anyway, thinking about all this, I would feel most comfortable with just taking the position that JavaCC21 was 1.x and we can start our numbering at 2.x perfectly well. And if anybody is curious, we can state the reasoning behind this in a FAQ. It seems legitimate enough to me, and frankly, if the legacy JavaCC project has the sheer audacity to put a 7.x version number on the thing, then who could reproach us for starting Congo at 2.x??

> 
> i also would ognore all 7.X and 0.95 ( others will not understand..)

Well, it's certainly true that these version numbers don't really mean that much usually anyway. But I guess that in a sane world, they would provide some very approximate guide about the maturity of the product. Of course, in that regard, the 7.x numbering on legacy JavaCC really subverts that concept completely. If that thing had something more like an honest version number, it would be more like 0.3 or something like that. I think that a 2.x for Congo, in that regard, is pretty legitimate. Well, there are nuances. Just in terms of pure Java usage, I think so, but it's not as mature for generating non-Java languages. Also, fault-tolerant is not so mature/tested. But quite a significant *superset* of the original JavaCC/JJTree functionality is really very mature.

So, I mean, us being on 1.0 when they are (supposedly) on 7.0.... Well, the whole thing is.... But, you asked my opinion, and I think that Congo starting at 2.0 is my preference. Again, our position is that JavaCC21 was effectively Congo 1.x....

> The question is also, whether current CongoCC I just include is ready to release.

Oh, sure, it can be released. Assuming it's based on what is currently the HEAD of the repository. And if the last commit has a green check-mark next to it, then this is good to go. That doesn't guarantee anything, of course, and our test coverage is far from perfect. But... we don't have anything else right now!

Oh, by the way, when you do a release build, it's better to use JDK 8. I mostly use this thing called [sdkman](https://sdkman.io) to switch JDK's. But we don't want to inadvertently put up a jarfile that requires JDK > 8 and the most reliable way of doing that is just to use JDK 8 to build.
